target "ArcGisDemo" do

pod 'AFNetworking', '~> 3.1.0'
pod 'Reachability', '~> 3.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'XMLReader', '~> 0.0.2'
pod 'Masonry', '~> 1.1.0'

end
